// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Container for Firebase credentials on both Android and iOS platforms.
///
/// This class wraps platform-specific credential objects. Each platform reads
/// only its own credential object and ignores the other, allowing a single
/// [PushCredentials] instance to carry credentials for both platforms at once.
///
/// This design enables multi-tenant scenarios where different Layrz clients
/// can inject their own Firebase project credentials at runtime. Credentials
/// can be hot-swapped by calling [LayrzPushPlatformChannel.setCredentials]
/// multiple times with different [PushCredentials] instances.
class PushCredentials {
  PushCredentials({
    this.android,
    this.ios,
  });

  /// Firebase credentials for Android, extracted from `google-services.json`.
  AndroidPushCredentials? android;

  /// Firebase credentials for iOS, extracted from `GoogleService-Info.plist`.
  IosPushCredentials? ios;

  List<Object?> _toList() {
    return <Object?>[
      android,
      ios,
    ];
  }

  Object encode() {
    return _toList();  }

  static PushCredentials decode(Object result) {
    result as List<Object?>;
    return PushCredentials(
      android: result[0] as AndroidPushCredentials?,
      ios: result[1] as IosPushCredentials?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PushCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(android, other.android) && _deepEquals(ios, other.ios);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Firebase credentials for Android, extracted from `google-services.json`.
///
/// These values must be obtained from the Firebase Console and bundled in
/// the app's `google-services.json` file during normal Firebase setup. However,
/// this plugin allows injecting credentials at runtime for multi-tenant support.
///
/// All required fields must be present for Firebase initialization to succeed
/// on the native Android side.
class AndroidPushCredentials {
  AndroidPushCredentials({
    required this.apiKey,
    required this.appId,
    required this.projectId,
    required this.messagingSenderId,
    this.storageBucket,
  });

  /// API key for the Android client.
  ///
  /// Found in `google-services.json` at `client[].api_key[].current_key`.
  String apiKey;

  /// Mobile SDK app ID for the Android client.
  ///
  /// Found in `google-services.json` at `client[].client_info.mobilesdk_app_id`.
  String appId;

  /// Firebase project ID.
  ///
  /// Found in `google-services.json` at `project_info.project_id`.
  /// This ID is shared across all platforms within the same Firebase project.
  String projectId;

  /// GCM (Google Cloud Messaging) sender ID, also known as the project number.
  ///
  /// Found in `google-services.json` at `project_info.project_number`.
  /// Used by FCM to identify the project when sending messages.
  String messagingSenderId;

  /// Cloud Storage bucket URL (optional).
  ///
  /// Found in `google-services.json` at `project_info.storage_bucket`.
  /// This field is optional and may be null.
  String? storageBucket;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidPushCredentials decode(Object result) {
    result as List<Object?>;
    return AndroidPushCredentials(
      apiKey: result[0]! as String,
      appId: result[1]! as String,
      projectId: result[2]! as String,
      messagingSenderId: result[3]! as String,
      storageBucket: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidPushCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) && _deepEquals(appId, other.appId) && _deepEquals(projectId, other.projectId) && _deepEquals(messagingSenderId, other.messagingSenderId) && _deepEquals(storageBucket, other.storageBucket);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Firebase credentials for iOS, extracted from `GoogleService-Info.plist`.
///
/// These values must be obtained from the Firebase Console and bundled in
/// the app's `GoogleService-Info.plist` file during normal Firebase setup. However,
/// this plugin allows injecting credentials at runtime for multi-tenant support.
///
/// All required fields must be present for Firebase initialization to succeed
/// on the native iOS side.
class IosPushCredentials {
  IosPushCredentials({
    required this.apiKey,
    required this.appId,
    required this.projectId,
    required this.messagingSenderId,
    this.storageBucket,
  });

  /// API key for the iOS client.
  ///
  /// Found in `GoogleService-Info.plist` with the key `API_KEY`.
  String apiKey;

  /// Firebase app ID for the iOS client.
  ///
  /// Found in `GoogleService-Info.plist` with the key `GOOGLE_APP_ID`.
  String appId;

  /// Firebase project ID.
  ///
  /// Found in `GoogleService-Info.plist` with the key `PROJECT_ID`.
  /// This ID is shared across all platforms within the same Firebase project.
  String projectId;

  /// GCM (Google Cloud Messaging) sender ID, also known as the project number.
  ///
  /// Found in `GoogleService-Info.plist` with the key `GCM_SENDER_ID`.
  /// Used by FCM to identify the project when sending messages.
  String messagingSenderId;

  /// Cloud Storage bucket URL (optional).
  ///
  /// Found in `GoogleService-Info.plist` with the key `STORAGE_BUCKET`.
  /// This field is optional and may be null.
  String? storageBucket;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosPushCredentials decode(Object result) {
    result as List<Object?>;
    return IosPushCredentials(
      apiKey: result[0]! as String,
      appId: result[1]! as String,
      projectId: result[2]! as String,
      messagingSenderId: result[3]! as String,
      storageBucket: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosPushCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) && _deepEquals(appId, other.appId) && _deepEquals(projectId, other.projectId) && _deepEquals(messagingSenderId, other.messagingSenderId) && _deepEquals(storageBucket, other.storageBucket);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A push notification received while the app is in foreground.
///
/// This object is passed to the [LayrzPushCallbackChannel.onPush] callback
/// when a notification arrives while the app is actively running. Notifications
/// received in the background or when the app is terminated are displayed by
/// the system directly and do not produce instances of this class.
///
/// The data payload is provided as a flat map of key-value string pairs, as
/// received from FCM.
class PushNotification {
  PushNotification({
    this.title,
    this.body,
    required this.data,
  });

  /// Title of the notification, if provided by the FCM message.
  ///
  /// May be null if no title was set on the upstream message.
  String? title;

  /// Body of the notification, if provided by the FCM message.
  ///
  /// May be null if no body was set on the upstream message.
  String? body;

  /// Custom data payload attached to the notification.
  ///
  /// This is a flat map of key-value pairs set by the application server
  /// or backend when sending the FCM message. Defaults to an empty map
  /// if no data was provided.
  Map<String, String> data;

  List<Object?> _toList() {
    return <Object?>[
      title,
      body,
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static PushNotification decode(Object result) {
    result as List<Object?>;
    return PushNotification(
      title: result[0] as String?,
      body: result[1] as String?,
      data: (result[2]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PushNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) && _deepEquals(body, other.body) && _deepEquals(data, other.data);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PushCredentials) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidPushCredentials) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is IosPushCredentials) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PushNotification) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PushCredentials.decode(readValue(buffer)!);
      case 130:
        return AndroidPushCredentials.decode(readValue(buffer)!);
      case 131:
        return IosPushCredentials.decode(readValue(buffer)!);
      case 132:
        return PushNotification.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API from Flutter to Native (via platform channels).
///
/// Provides the primary interface for managing Firebase Cloud Messaging (FCM)
/// credentials and subscriptions on native platforms. All methods are async
/// and communicate with native code through Pigeon-generated platform channels.
class LayrzPushPlatformChannel {
  /// Constructor for [LayrzPushPlatformChannel].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LayrzPushPlatformChannel({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Injects (or replaces) the Firebase credentials at runtime.
  ///
  /// This method allows hot-swapping between different Firebase projects without
  /// restarting the app, enabling multi-tenant support. Each platform reads only
  /// its own credentials object (Android reads [PushCredentials.android], iOS reads
  /// [PushCredentials.ios]) and ignores the other.
  ///
  /// If a Firebase app is already configured on the native side, it is deleted and
  /// re-initialized with the new credentials. This ensures the app stays connected
  /// to the correct FCM backend for the current tenant.
  ///
  /// Returns `true` if credentials were successfully applied, `false` otherwise.
  Future<bool> setCredentials({required PushCredentials credentials}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setCredentials$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[credentials]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Persists the Layrz device ID securely on the device.
  ///
  /// On Android, the device ID is encrypted using AES-GCM and stored in
  /// SharedPreferences backed by Android Keystore. On iOS, it is stored in
  /// Keychain (which survives app uninstall).
  ///
  /// The device ID defines the FCM topic that [subscribe] and [unsubscribe]
  /// will target, following the format `device_{deviceId}`.
  ///
  /// Must be called before [subscribe] and [unsubscribe]; they will return
  /// `false` if no device ID is set.
  ///
  /// Returns `true` if the device ID was successfully persisted, `false` otherwise.
  Future<bool> setDeviceId({required String deviceId}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setDeviceId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Subscribes to the `device_{deviceId}` FCM topic.
  ///
  /// Requires both [setCredentials] and [setDeviceId] to have been called
  /// successfully first. If either is missing, this method returns `false`.
  ///
  /// On first subscribe after app install, FCM must fetch its registration token
  /// from Google Mobile Services (GMS). This can take a considerable time (observed
  /// up to 75 seconds) due to GMS communication and potential transient error
  /// retries. The returned Future completes once FCM finishes initialization.
  ///
  /// The subscription list is tracked locally; subsequent calls to [getSubscriptions]
  /// will reflect the newly added topic.
  ///
  /// Returns `true` if the subscription succeeded, `false` if credentials or device
  /// ID are missing, or if the native subscribe operation failed.
  Future<bool> subscribe() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.subscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Unsubscribes from the `device_{deviceId}` FCM topic.
  ///
  /// Requires [setDeviceId] to have been called first. Returns `false` if no
  /// device ID is set or if the unsubscribe operation fails.
  ///
  /// The subscription list is tracked locally; subsequent calls to [getSubscriptions]
  /// will reflect the removal of the topic.
  ///
  /// Returns `true` if the unsubscription succeeded, `false` otherwise.
  Future<bool> unsubscribe() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.unsubscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Returns the list of currently subscribed FCM topics.
  ///
  /// FCM does not provide a native API to query the full list of subscribed topics,
  /// so this plugin maintains a local list that is updated on each [subscribe] and
  /// [unsubscribe] call. This method returns that locally-tracked list.
  ///
  /// The list should contain topic strings like `device_12345` for subscribed topics.
  /// If no subscriptions exist, an empty list is returned.
  Future<List<String>> getSubscriptions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.getSubscriptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}

/// Flutter API from Native to Flutter (via platform channels).
///
/// Provides a callback interface for the native platform to invoke Flutter
/// when events occur. This is implemented and set up by the Dart platform
/// implementation to receive foreground push notifications.
abstract class LayrzPushCallbackChannel {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when a push notification arrives while the app is in foreground.
  ///
  /// This callback fires only when the app is actively running and visible to
  /// the user. When the app is in the background or terminated, the system will
  /// display the notification directly (with a system banner) and this callback
  /// will not be invoked.
  ///
  /// The [notification] contains the title, body, and custom data payload sent
  /// by the FCM backend.
  void onPush(PushNotification notification);

  static void setUp(LayrzPushCallbackChannel? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_push.LayrzPushCallbackChannel.onPush$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PushNotification arg_notification = args[0]! as PushNotification;
          try {
            api.onPush(arg_notification);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
