// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Firebase credentials for both platforms. Each platform is optional,
/// the native side picks its own.
class PushCredentials {
  PushCredentials({
    this.android,
    this.ios,
  });

  AndroidPushCredentials? android;

  IosPushCredentials? ios;

  List<Object?> _toList() {
    return <Object?>[
      android,
      ios,
    ];
  }

  Object encode() {
    return _toList();  }

  static PushCredentials decode(Object result) {
    result as List<Object?>;
    return PushCredentials(
      android: result[0] as AndroidPushCredentials?,
      ios: result[1] as IosPushCredentials?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PushCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(android, other.android) && _deepEquals(ios, other.ios);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Firebase credentials for Android, equivalent to the values found in
/// `google-services.json`.
class AndroidPushCredentials {
  AndroidPushCredentials({
    required this.apiKey,
    required this.appId,
    required this.projectId,
    required this.messagingSenderId,
    this.storageBucket,
  });

  /// `client[].api_key[].current_key` in google-services.json
  String apiKey;

  /// `client[].client_info.mobilesdk_app_id` in google-services.json
  String appId;

  /// `project_info.project_id` in google-services.json
  String projectId;

  /// `project_info.project_number` in google-services.json
  String messagingSenderId;

  /// `project_info.storage_bucket` in google-services.json
  String? storageBucket;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidPushCredentials decode(Object result) {
    result as List<Object?>;
    return AndroidPushCredentials(
      apiKey: result[0]! as String,
      appId: result[1]! as String,
      projectId: result[2]! as String,
      messagingSenderId: result[3]! as String,
      storageBucket: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidPushCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) && _deepEquals(appId, other.appId) && _deepEquals(projectId, other.projectId) && _deepEquals(messagingSenderId, other.messagingSenderId) && _deepEquals(storageBucket, other.storageBucket);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Firebase credentials for iOS, equivalent to the values found in
/// `GoogleService-Info.plist`.
class IosPushCredentials {
  IosPushCredentials({
    required this.apiKey,
    required this.appId,
    required this.projectId,
    required this.messagingSenderId,
    this.storageBucket,
  });

  /// `API_KEY` in GoogleService-Info.plist
  String apiKey;

  /// `GOOGLE_APP_ID` in GoogleService-Info.plist
  String appId;

  /// `PROJECT_ID` in GoogleService-Info.plist
  String projectId;

  /// `GCM_SENDER_ID` in GoogleService-Info.plist
  String messagingSenderId;

  /// `STORAGE_BUCKET` in GoogleService-Info.plist
  String? storageBucket;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosPushCredentials decode(Object result) {
    result as List<Object?>;
    return IosPushCredentials(
      apiKey: result[0]! as String,
      appId: result[1]! as String,
      projectId: result[2]! as String,
      messagingSenderId: result[3]! as String,
      storageBucket: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosPushCredentials || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) && _deepEquals(appId, other.appId) && _deepEquals(projectId, other.projectId) && _deepEquals(messagingSenderId, other.messagingSenderId) && _deepEquals(storageBucket, other.storageBucket);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A push notification received while the app is in foreground.
class PushNotification {
  PushNotification({
    this.title,
    this.body,
    required this.data,
  });

  /// Title of the notification, if any.
  String? title;

  /// Body of the notification, if any.
  String? body;

  /// Custom data payload attached to the notification.
  Map<String, String> data;

  List<Object?> _toList() {
    return <Object?>[
      title,
      body,
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static PushNotification decode(Object result) {
    result as List<Object?>;
    return PushNotification(
      title: result[0] as String?,
      body: result[1] as String?,
      data: (result[2]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PushNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) && _deepEquals(body, other.body) && _deepEquals(data, other.data);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PushCredentials) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidPushCredentials) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is IosPushCredentials) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PushNotification) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PushCredentials.decode(readValue(buffer)!);
      case 130:
        return AndroidPushCredentials.decode(readValue(buffer)!);
      case 131:
        return IosPushCredentials.decode(readValue(buffer)!);
      case 132:
        return PushNotification.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LayrzPushPlatformChannel {
  /// Constructor for [LayrzPushPlatformChannel].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LayrzPushPlatformChannel({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Injects (or replaces) the Firebase credentials at runtime.
  ///
  /// Each platform reads its own sub-object and ignores the other one.
  /// If a Firebase app is already configured, it's deleted and re-created
  /// with the new options.
  Future<bool> setCredentials({required PushCredentials credentials}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setCredentials$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[credentials]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Persists the Layrz device ID securely on the device.
  ///
  /// The device ID defines the FCM topic used by [subscribe] and
  /// [unsubscribe], following the format `device_{deviceId}`.
  Future<bool> setDeviceId({required String deviceId}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setDeviceId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Subscribes to the `device_{deviceId}` FCM topic.
  ///
  /// Requires [setCredentials] and [setDeviceId] to be called first.
  Future<bool> subscribe() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.subscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Unsubscribes from the `device_{deviceId}` FCM topic.
  Future<bool> unsubscribe() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.unsubscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Returns the list of currently subscribed topics.
  ///
  /// FCM does not provide a native API for this, so the list is tracked
  /// locally on each subscribe/unsubscribe call.
  Future<List<String>> getSubscriptions() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.getSubscriptions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }
}

abstract class LayrzPushCallbackChannel {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when a push notification arrives while the app is in foreground.
  void onPush(PushNotification notification);

  static void setUp(LayrzPushCallbackChannel? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.layrz_push.LayrzPushCallbackChannel.onPush$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final PushNotification arg_notification = args[0]! as PushNotification;
          try {
            api.onPush(arg_notification);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
