// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.layrz.layrz_push

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LayrzPushPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Firebase credentials for both platforms. Each platform is optional,
 * the native side picks its own.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PushCredentials (
  val android: AndroidPushCredentials? = null,
  val ios: IosPushCredentials? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushCredentials {
      val android = pigeonVar_list[0] as AndroidPushCredentials?
      val ios = pigeonVar_list[1] as IosPushCredentials?
      return PushCredentials(android, ios)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      android,
      ios,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PushCredentials
    return LayrzPushPigeonUtils.deepEquals(this.android, other.android) && LayrzPushPigeonUtils.deepEquals(this.ios, other.ios)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.android)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.ios)
    return result
  }
}

/**
 * Firebase credentials for Android, equivalent to the values found in
 * `google-services.json`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidPushCredentials (
  /** `client[].api_key[].current_key` in google-services.json */
  val apiKey: String,
  /** `client[].client_info.mobilesdk_app_id` in google-services.json */
  val appId: String,
  /** `project_info.project_id` in google-services.json */
  val projectId: String,
  /** `project_info.project_number` in google-services.json */
  val messagingSenderId: String,
  /** `project_info.storage_bucket` in google-services.json */
  val storageBucket: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidPushCredentials {
      val apiKey = pigeonVar_list[0] as String
      val appId = pigeonVar_list[1] as String
      val projectId = pigeonVar_list[2] as String
      val messagingSenderId = pigeonVar_list[3] as String
      val storageBucket = pigeonVar_list[4] as String?
      return AndroidPushCredentials(apiKey, appId, projectId, messagingSenderId, storageBucket)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidPushCredentials
    return LayrzPushPigeonUtils.deepEquals(this.apiKey, other.apiKey) && LayrzPushPigeonUtils.deepEquals(this.appId, other.appId) && LayrzPushPigeonUtils.deepEquals(this.projectId, other.projectId) && LayrzPushPigeonUtils.deepEquals(this.messagingSenderId, other.messagingSenderId) && LayrzPushPigeonUtils.deepEquals(this.storageBucket, other.storageBucket)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.appId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.projectId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.messagingSenderId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.storageBucket)
    return result
  }
}

/**
 * Firebase credentials for iOS, equivalent to the values found in
 * `GoogleService-Info.plist`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosPushCredentials (
  /** `API_KEY` in GoogleService-Info.plist */
  val apiKey: String,
  /** `GOOGLE_APP_ID` in GoogleService-Info.plist */
  val appId: String,
  /** `PROJECT_ID` in GoogleService-Info.plist */
  val projectId: String,
  /** `GCM_SENDER_ID` in GoogleService-Info.plist */
  val messagingSenderId: String,
  /** `STORAGE_BUCKET` in GoogleService-Info.plist */
  val storageBucket: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosPushCredentials {
      val apiKey = pigeonVar_list[0] as String
      val appId = pigeonVar_list[1] as String
      val projectId = pigeonVar_list[2] as String
      val messagingSenderId = pigeonVar_list[3] as String
      val storageBucket = pigeonVar_list[4] as String?
      return IosPushCredentials(apiKey, appId, projectId, messagingSenderId, storageBucket)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IosPushCredentials
    return LayrzPushPigeonUtils.deepEquals(this.apiKey, other.apiKey) && LayrzPushPigeonUtils.deepEquals(this.appId, other.appId) && LayrzPushPigeonUtils.deepEquals(this.projectId, other.projectId) && LayrzPushPigeonUtils.deepEquals(this.messagingSenderId, other.messagingSenderId) && LayrzPushPigeonUtils.deepEquals(this.storageBucket, other.storageBucket)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.appId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.projectId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.messagingSenderId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.storageBucket)
    return result
  }
}

/**
 * A push notification received while the app is in foreground.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PushNotification (
  /** Title of the notification, if any. */
  val title: String? = null,
  /** Body of the notification, if any. */
  val body: String? = null,
  /** Custom data payload attached to the notification. */
  val data: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushNotification {
      val title = pigeonVar_list[0] as String?
      val body = pigeonVar_list[1] as String?
      val data = pigeonVar_list[2] as Map<String, String>
      return PushNotification(title, body, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      body,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PushNotification
    return LayrzPushPigeonUtils.deepEquals(this.title, other.title) && LayrzPushPigeonUtils.deepEquals(this.body, other.body) && LayrzPushPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.title)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.body)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.data)
    return result
  }
}
private open class LayrzPushPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushCredentials.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidPushCredentials.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosPushCredentials.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushNotification.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PushCredentials -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AndroidPushCredentials -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is IosPushCredentials -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PushNotification -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LayrzPushPlatformChannel {
  /**
   * Injects (or replaces) the Firebase credentials at runtime.
   *
   * Each platform reads its own sub-object and ignores the other one.
   * If a Firebase app is already configured, it's deleted and re-created
   * with the new options.
   */
  fun setCredentials(credentials: PushCredentials, callback: (Result<Boolean>) -> Unit)
  /**
   * Persists the Layrz device ID securely on the device.
   *
   * The device ID defines the FCM topic used by [subscribe] and
   * [unsubscribe], following the format `device_{deviceId}`.
   */
  fun setDeviceId(deviceId: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Subscribes to the `device_{deviceId}` FCM topic.
   *
   * Requires [setCredentials] and [setDeviceId] to be called first.
   */
  fun subscribe(callback: (Result<Boolean>) -> Unit)
  /** Unsubscribes from the `device_{deviceId}` FCM topic. */
  fun unsubscribe(callback: (Result<Boolean>) -> Unit)
  /**
   * Returns the list of currently subscribed topics.
   *
   * FCM does not provide a native API for this, so the list is tracked
   * locally on each subscribe/unsubscribe call.
   */
  fun getSubscriptions(callback: (Result<List<String>>) -> Unit)

  companion object {
    /** The codec used by LayrzPushPlatformChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzPushPigeonCodec()
    }
    /** Sets up an instance of `LayrzPushPlatformChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LayrzPushPlatformChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as PushCredentials
            api.setCredentials(credentialsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setDeviceId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.setDeviceId(deviceIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.subscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.subscribe{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.unsubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unsubscribe{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.getSubscriptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSubscriptions{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LayrzPushCallbackChannel(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LayrzPushCallbackChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzPushPigeonCodec()
    }
  }
  /** Called when a push notification arrives while the app is in foreground. */
  fun onPush(notificationArg: PushNotification, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_push.LayrzPushCallbackChannel.onPush$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(notificationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzPushPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
