// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.layrz.layrz_push

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LayrzPushPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Container for Firebase credentials on both Android and iOS platforms.
 *
 * This class wraps platform-specific credential objects. Each platform reads
 * only its own credential object and ignores the other, allowing a single
 * [PushCredentials] instance to carry credentials for both platforms at once.
 *
 * This design enables multi-tenant scenarios where different Layrz clients
 * can inject their own Firebase project credentials at runtime. Credentials
 * can be hot-swapped by calling [LayrzPushPlatformChannel.setCredentials]
 * multiple times with different [PushCredentials] instances.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PushCredentials (
  /** Firebase credentials for Android, extracted from `google-services.json`. */
  val android: AndroidPushCredentials? = null,
  /** Firebase credentials for iOS, extracted from `GoogleService-Info.plist`. */
  val ios: IosPushCredentials? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushCredentials {
      val android = pigeonVar_list[0] as AndroidPushCredentials?
      val ios = pigeonVar_list[1] as IosPushCredentials?
      return PushCredentials(android, ios)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      android,
      ios,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PushCredentials
    return LayrzPushPigeonUtils.deepEquals(this.android, other.android) && LayrzPushPigeonUtils.deepEquals(this.ios, other.ios)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.android)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.ios)
    return result
  }
}

/**
 * Firebase credentials for Android, extracted from `google-services.json`.
 *
 * These values must be obtained from the Firebase Console and bundled in
 * the app's `google-services.json` file during normal Firebase setup. However,
 * this plugin allows injecting credentials at runtime for multi-tenant support.
 *
 * All required fields must be present for Firebase initialization to succeed
 * on the native Android side.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidPushCredentials (
  /**
   * API key for the Android client.
   *
   * Found in `google-services.json` at `client[].api_key[].current_key`.
   */
  val apiKey: String,
  /**
   * Mobile SDK app ID for the Android client.
   *
   * Found in `google-services.json` at `client[].client_info.mobilesdk_app_id`.
   */
  val appId: String,
  /**
   * Firebase project ID.
   *
   * Found in `google-services.json` at `project_info.project_id`.
   * This ID is shared across all platforms within the same Firebase project.
   */
  val projectId: String,
  /**
   * GCM (Google Cloud Messaging) sender ID, also known as the project number.
   *
   * Found in `google-services.json` at `project_info.project_number`.
   * Used by FCM to identify the project when sending messages.
   */
  val messagingSenderId: String,
  /**
   * Cloud Storage bucket URL (optional).
   *
   * Found in `google-services.json` at `project_info.storage_bucket`.
   * This field is optional and may be null.
   */
  val storageBucket: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidPushCredentials {
      val apiKey = pigeonVar_list[0] as String
      val appId = pigeonVar_list[1] as String
      val projectId = pigeonVar_list[2] as String
      val messagingSenderId = pigeonVar_list[3] as String
      val storageBucket = pigeonVar_list[4] as String?
      return AndroidPushCredentials(apiKey, appId, projectId, messagingSenderId, storageBucket)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidPushCredentials
    return LayrzPushPigeonUtils.deepEquals(this.apiKey, other.apiKey) && LayrzPushPigeonUtils.deepEquals(this.appId, other.appId) && LayrzPushPigeonUtils.deepEquals(this.projectId, other.projectId) && LayrzPushPigeonUtils.deepEquals(this.messagingSenderId, other.messagingSenderId) && LayrzPushPigeonUtils.deepEquals(this.storageBucket, other.storageBucket)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.appId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.projectId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.messagingSenderId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.storageBucket)
    return result
  }
}

/**
 * Firebase credentials for iOS, extracted from `GoogleService-Info.plist`.
 *
 * These values must be obtained from the Firebase Console and bundled in
 * the app's `GoogleService-Info.plist` file during normal Firebase setup. However,
 * this plugin allows injecting credentials at runtime for multi-tenant support.
 *
 * All required fields must be present for Firebase initialization to succeed
 * on the native iOS side.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosPushCredentials (
  /**
   * API key for the iOS client.
   *
   * Found in `GoogleService-Info.plist` with the key `API_KEY`.
   */
  val apiKey: String,
  /**
   * Firebase app ID for the iOS client.
   *
   * Found in `GoogleService-Info.plist` with the key `GOOGLE_APP_ID`.
   */
  val appId: String,
  /**
   * Firebase project ID.
   *
   * Found in `GoogleService-Info.plist` with the key `PROJECT_ID`.
   * This ID is shared across all platforms within the same Firebase project.
   */
  val projectId: String,
  /**
   * GCM (Google Cloud Messaging) sender ID, also known as the project number.
   *
   * Found in `GoogleService-Info.plist` with the key `GCM_SENDER_ID`.
   * Used by FCM to identify the project when sending messages.
   */
  val messagingSenderId: String,
  /**
   * Cloud Storage bucket URL (optional).
   *
   * Found in `GoogleService-Info.plist` with the key `STORAGE_BUCKET`.
   * This field is optional and may be null.
   */
  val storageBucket: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosPushCredentials {
      val apiKey = pigeonVar_list[0] as String
      val appId = pigeonVar_list[1] as String
      val projectId = pigeonVar_list[2] as String
      val messagingSenderId = pigeonVar_list[3] as String
      val storageBucket = pigeonVar_list[4] as String?
      return IosPushCredentials(apiKey, appId, projectId, messagingSenderId, storageBucket)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IosPushCredentials
    return LayrzPushPigeonUtils.deepEquals(this.apiKey, other.apiKey) && LayrzPushPigeonUtils.deepEquals(this.appId, other.appId) && LayrzPushPigeonUtils.deepEquals(this.projectId, other.projectId) && LayrzPushPigeonUtils.deepEquals(this.messagingSenderId, other.messagingSenderId) && LayrzPushPigeonUtils.deepEquals(this.storageBucket, other.storageBucket)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.appId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.projectId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.messagingSenderId)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.storageBucket)
    return result
  }
}

/**
 * A push notification received while the app is in foreground.
 *
 * This object is passed to the [LayrzPushCallbackChannel.onPush] callback
 * when a notification arrives while the app is actively running. Notifications
 * received in the background or when the app is terminated are displayed by
 * the system directly and do not produce instances of this class.
 *
 * The data payload is provided as a flat map of key-value string pairs, as
 * received from FCM.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PushNotification (
  /**
   * Title of the notification, if provided by the FCM message.
   *
   * May be null if no title was set on the upstream message.
   */
  val title: String? = null,
  /**
   * Body of the notification, if provided by the FCM message.
   *
   * May be null if no body was set on the upstream message.
   */
  val body: String? = null,
  /**
   * Custom data payload attached to the notification.
   *
   * This is a flat map of key-value pairs set by the application server
   * or backend when sending the FCM message. Defaults to an empty map
   * if no data was provided.
   */
  val data: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushNotification {
      val title = pigeonVar_list[0] as String?
      val body = pigeonVar_list[1] as String?
      val data = pigeonVar_list[2] as Map<String, String>
      return PushNotification(title, body, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      body,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PushNotification
    return LayrzPushPigeonUtils.deepEquals(this.title, other.title) && LayrzPushPigeonUtils.deepEquals(this.body, other.body) && LayrzPushPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.title)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.body)
    result = 31 * result + LayrzPushPigeonUtils.deepHash(this.data)
    return result
  }
}
private open class LayrzPushPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushCredentials.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidPushCredentials.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosPushCredentials.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushNotification.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PushCredentials -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AndroidPushCredentials -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is IosPushCredentials -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PushNotification -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API from Flutter to Native (via platform channels).
 *
 * Provides the primary interface for managing Firebase Cloud Messaging (FCM)
 * credentials and subscriptions on native platforms. All methods are async
 * and communicate with native code through Pigeon-generated platform channels.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface LayrzPushPlatformChannel {
  /**
   * Injects (or replaces) the Firebase credentials at runtime.
   *
   * This method allows hot-swapping between different Firebase projects without
   * restarting the app, enabling multi-tenant support. Each platform reads only
   * its own credentials object (Android reads [PushCredentials.android], iOS reads
   * [PushCredentials.ios]) and ignores the other.
   *
   * If a Firebase app is already configured on the native side, it is deleted and
   * re-initialized with the new credentials. This ensures the app stays connected
   * to the correct FCM backend for the current tenant.
   *
   * Returns `true` if credentials were successfully applied, `false` otherwise.
   */
  fun setCredentials(credentials: PushCredentials, callback: (Result<Boolean>) -> Unit)
  /**
   * Persists the Layrz device ID securely on the device.
   *
   * On Android, the device ID is encrypted using AES-GCM and stored in
   * SharedPreferences backed by Android Keystore. On iOS, it is stored in
   * Keychain (which survives app uninstall).
   *
   * The device ID defines the FCM topic that [subscribe] and [unsubscribe]
   * will target, following the format `device_{deviceId}`.
   *
   * Must be called before [subscribe] and [unsubscribe]; they will return
   * `false` if no device ID is set.
   *
   * Returns `true` if the device ID was successfully persisted, `false` otherwise.
   */
  fun setDeviceId(deviceId: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Subscribes to the `device_{deviceId}` FCM topic.
   *
   * Requires both [setCredentials] and [setDeviceId] to have been called
   * successfully first. If either is missing, this method returns `false`.
   *
   * On first subscribe after app install, FCM must fetch its registration token
   * from Google Mobile Services (GMS). This can take a considerable time (observed
   * up to 75 seconds) due to GMS communication and potential transient error
   * retries. The returned Future completes once FCM finishes initialization.
   *
   * The subscription list is tracked locally; subsequent calls to [getSubscriptions]
   * will reflect the newly added topic.
   *
   * Returns `true` if the subscription succeeded, `false` if credentials or device
   * ID are missing, or if the native subscribe operation failed.
   */
  fun subscribe(callback: (Result<Boolean>) -> Unit)
  /**
   * Unsubscribes from the `device_{deviceId}` FCM topic.
   *
   * Requires [setDeviceId] to have been called first. Returns `false` if no
   * device ID is set or if the unsubscribe operation fails.
   *
   * The subscription list is tracked locally; subsequent calls to [getSubscriptions]
   * will reflect the removal of the topic.
   *
   * Returns `true` if the unsubscription succeeded, `false` otherwise.
   */
  fun unsubscribe(callback: (Result<Boolean>) -> Unit)
  /**
   * Returns the list of currently subscribed FCM topics.
   *
   * FCM does not provide a native API to query the full list of subscribed topics,
   * so this plugin maintains a local list that is updated on each [subscribe] and
   * [unsubscribe] call. This method returns that locally-tracked list.
   *
   * The list should contain topic strings like `device_12345` for subscribed topics.
   * If no subscriptions exist, an empty list is returned.
   */
  fun getSubscriptions(callback: (Result<List<String>>) -> Unit)

  companion object {
    /** The codec used by LayrzPushPlatformChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzPushPigeonCodec()
    }
    /** Sets up an instance of `LayrzPushPlatformChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LayrzPushPlatformChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as PushCredentials
            api.setCredentials(credentialsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setDeviceId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.setDeviceId(deviceIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.subscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.subscribe{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.unsubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unsubscribe{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.getSubscriptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSubscriptions{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LayrzPushPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LayrzPushPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API from Native to Flutter (via platform channels).
 *
 * Provides a callback interface for the native platform to invoke Flutter
 * when events occur. This is implemented and set up by the Dart platform
 * implementation to receive foreground push notifications.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class LayrzPushCallbackChannel(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LayrzPushCallbackChannel. */
    val codec: MessageCodec<Any?> by lazy {
      LayrzPushPigeonCodec()
    }
  }
  /**
   * Called when a push notification arrives while the app is in foreground.
   *
   * This callback fires only when the app is actively running and visible to
   * the user. When the app is in the background or terminated, the system will
   * display the notification directly (with a system banner) and this callback
   * will not be invoked.
   *
   * The [notification] contains the title, body, and custom data payload sent
   * by the FCM backend.
   */
  fun onPush(notificationArg: PushNotification, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.layrz_push.LayrzPushCallbackChannel.onPush$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(notificationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LayrzPushPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
