// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsLayrzPush(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashLayrzPush(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsLayrzPush(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsLayrzPush(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsLayrzPush(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsLayrzPush(lhsKey, rhsKey) {
          if deepEqualsLayrzPush(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsLayrzPush(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashLayrzPush(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashLayrzPush(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashLayrzPush(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashLayrzPush(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashLayrzPush(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashLayrzPush(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Container for Firebase credentials on both Android and iOS platforms.
///
/// This class wraps platform-specific credential objects. Each platform reads
/// only its own credential object and ignores the other, allowing a single
/// [PushCredentials] instance to carry credentials for both platforms at once.
///
/// This design enables multi-tenant scenarios where different Layrz clients
/// can inject their own Firebase project credentials at runtime. Credentials
/// can be hot-swapped by calling [LayrzPushPlatformChannel.setCredentials]
/// multiple times with different [PushCredentials] instances.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PushCredentials: Hashable {
  /// Firebase credentials for Android, extracted from `google-services.json`.
  var android: AndroidPushCredentials? = nil
  /// Firebase credentials for iOS, extracted from `GoogleService-Info.plist`.
  var ios: IosPushCredentials? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PushCredentials? {
    let android: AndroidPushCredentials? = nilOrValue(pigeonVar_list[0])
    let ios: IosPushCredentials? = nilOrValue(pigeonVar_list[1])

    return PushCredentials(
      android: android,
      ios: ios
    )
  }
  func toList() -> [Any?] {
    return [
      android,
      ios,
    ]
  }
  static func == (lhs: PushCredentials, rhs: PushCredentials) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzPush(lhs.android, rhs.android) && deepEqualsLayrzPush(lhs.ios, rhs.ios)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PushCredentials")
    deepHashLayrzPush(value: android, hasher: &hasher)
    deepHashLayrzPush(value: ios, hasher: &hasher)
  }
}

/// Firebase credentials for Android, extracted from `google-services.json`.
///
/// These values must be obtained from the Firebase Console and bundled in
/// the app's `google-services.json` file during normal Firebase setup. However,
/// this plugin allows injecting credentials at runtime for multi-tenant support.
///
/// All required fields must be present for Firebase initialization to succeed
/// on the native Android side.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidPushCredentials: Hashable {
  /// API key for the Android client.
  ///
  /// Found in `google-services.json` at `client[].api_key[].current_key`.
  var apiKey: String
  /// Mobile SDK app ID for the Android client.
  ///
  /// Found in `google-services.json` at `client[].client_info.mobilesdk_app_id`.
  var appId: String
  /// Firebase project ID.
  ///
  /// Found in `google-services.json` at `project_info.project_id`.
  /// This ID is shared across all platforms within the same Firebase project.
  var projectId: String
  /// GCM (Google Cloud Messaging) sender ID, also known as the project number.
  ///
  /// Found in `google-services.json` at `project_info.project_number`.
  /// Used by FCM to identify the project when sending messages.
  var messagingSenderId: String
  /// Cloud Storage bucket URL (optional).
  ///
  /// Found in `google-services.json` at `project_info.storage_bucket`.
  /// This field is optional and may be null.
  var storageBucket: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidPushCredentials? {
    let apiKey = pigeonVar_list[0] as! String
    let appId = pigeonVar_list[1] as! String
    let projectId = pigeonVar_list[2] as! String
    let messagingSenderId = pigeonVar_list[3] as! String
    let storageBucket: String? = nilOrValue(pigeonVar_list[4])

    return AndroidPushCredentials(
      apiKey: apiKey,
      appId: appId,
      projectId: projectId,
      messagingSenderId: messagingSenderId,
      storageBucket: storageBucket
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    ]
  }
  static func == (lhs: AndroidPushCredentials, rhs: AndroidPushCredentials) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzPush(lhs.apiKey, rhs.apiKey) && deepEqualsLayrzPush(lhs.appId, rhs.appId) && deepEqualsLayrzPush(lhs.projectId, rhs.projectId) && deepEqualsLayrzPush(lhs.messagingSenderId, rhs.messagingSenderId) && deepEqualsLayrzPush(lhs.storageBucket, rhs.storageBucket)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AndroidPushCredentials")
    deepHashLayrzPush(value: apiKey, hasher: &hasher)
    deepHashLayrzPush(value: appId, hasher: &hasher)
    deepHashLayrzPush(value: projectId, hasher: &hasher)
    deepHashLayrzPush(value: messagingSenderId, hasher: &hasher)
    deepHashLayrzPush(value: storageBucket, hasher: &hasher)
  }
}

/// Firebase credentials for iOS, extracted from `GoogleService-Info.plist`.
///
/// These values must be obtained from the Firebase Console and bundled in
/// the app's `GoogleService-Info.plist` file during normal Firebase setup. However,
/// this plugin allows injecting credentials at runtime for multi-tenant support.
///
/// All required fields must be present for Firebase initialization to succeed
/// on the native iOS side.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IosPushCredentials: Hashable {
  /// API key for the iOS client.
  ///
  /// Found in `GoogleService-Info.plist` with the key `API_KEY`.
  var apiKey: String
  /// Firebase app ID for the iOS client.
  ///
  /// Found in `GoogleService-Info.plist` with the key `GOOGLE_APP_ID`.
  var appId: String
  /// Firebase project ID.
  ///
  /// Found in `GoogleService-Info.plist` with the key `PROJECT_ID`.
  /// This ID is shared across all platforms within the same Firebase project.
  var projectId: String
  /// GCM (Google Cloud Messaging) sender ID, also known as the project number.
  ///
  /// Found in `GoogleService-Info.plist` with the key `GCM_SENDER_ID`.
  /// Used by FCM to identify the project when sending messages.
  var messagingSenderId: String
  /// Cloud Storage bucket URL (optional).
  ///
  /// Found in `GoogleService-Info.plist` with the key `STORAGE_BUCKET`.
  /// This field is optional and may be null.
  var storageBucket: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IosPushCredentials? {
    let apiKey = pigeonVar_list[0] as! String
    let appId = pigeonVar_list[1] as! String
    let projectId = pigeonVar_list[2] as! String
    let messagingSenderId = pigeonVar_list[3] as! String
    let storageBucket: String? = nilOrValue(pigeonVar_list[4])

    return IosPushCredentials(
      apiKey: apiKey,
      appId: appId,
      projectId: projectId,
      messagingSenderId: messagingSenderId,
      storageBucket: storageBucket
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      storageBucket,
    ]
  }
  static func == (lhs: IosPushCredentials, rhs: IosPushCredentials) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzPush(lhs.apiKey, rhs.apiKey) && deepEqualsLayrzPush(lhs.appId, rhs.appId) && deepEqualsLayrzPush(lhs.projectId, rhs.projectId) && deepEqualsLayrzPush(lhs.messagingSenderId, rhs.messagingSenderId) && deepEqualsLayrzPush(lhs.storageBucket, rhs.storageBucket)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IosPushCredentials")
    deepHashLayrzPush(value: apiKey, hasher: &hasher)
    deepHashLayrzPush(value: appId, hasher: &hasher)
    deepHashLayrzPush(value: projectId, hasher: &hasher)
    deepHashLayrzPush(value: messagingSenderId, hasher: &hasher)
    deepHashLayrzPush(value: storageBucket, hasher: &hasher)
  }
}

/// A push notification received while the app is in foreground.
///
/// This object is passed to the [LayrzPushCallbackChannel.onPush] callback
/// when a notification arrives while the app is actively running. Notifications
/// received in the background or when the app is terminated are displayed by
/// the system directly and do not produce instances of this class.
///
/// The data payload is provided as a flat map of key-value string pairs, as
/// received from FCM.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PushNotification: Hashable {
  /// Title of the notification, if provided by the FCM message.
  ///
  /// May be null if no title was set on the upstream message.
  var title: String? = nil
  /// Body of the notification, if provided by the FCM message.
  ///
  /// May be null if no body was set on the upstream message.
  var body: String? = nil
  /// Custom data payload attached to the notification.
  ///
  /// This is a flat map of key-value pairs set by the application server
  /// or backend when sending the FCM message. Defaults to an empty map
  /// if no data was provided.
  var data: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PushNotification? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let body: String? = nilOrValue(pigeonVar_list[1])
    let data = pigeonVar_list[2] as! [String: String]

    return PushNotification(
      title: title,
      body: body,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      body,
      data,
    ]
  }
  static func == (lhs: PushNotification, rhs: PushNotification) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsLayrzPush(lhs.title, rhs.title) && deepEqualsLayrzPush(lhs.body, rhs.body) && deepEqualsLayrzPush(lhs.data, rhs.data)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PushNotification")
    deepHashLayrzPush(value: title, hasher: &hasher)
    deepHashLayrzPush(value: body, hasher: &hasher)
    deepHashLayrzPush(value: data, hasher: &hasher)
  }
}

private class LayrzPushPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PushCredentials.fromList(self.readValue() as! [Any?])
    case 130:
      return AndroidPushCredentials.fromList(self.readValue() as! [Any?])
    case 131:
      return IosPushCredentials.fromList(self.readValue() as! [Any?])
    case 132:
      return PushNotification.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LayrzPushPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PushCredentials {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidPushCredentials {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? IosPushCredentials {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PushNotification {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LayrzPushPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LayrzPushPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LayrzPushPigeonCodecWriter(data: data)
  }
}

class LayrzPushPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LayrzPushPigeonCodec(readerWriter: LayrzPushPigeonCodecReaderWriter())
}


/// Host API from Flutter to Native (via platform channels).
///
/// Provides the primary interface for managing Firebase Cloud Messaging (FCM)
/// credentials and subscriptions on native platforms. All methods are async
/// and communicate with native code through Pigeon-generated platform channels.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LayrzPushPlatformChannel {
  /// Injects (or replaces) the Firebase credentials at runtime.
  ///
  /// This method allows hot-swapping between different Firebase projects without
  /// restarting the app, enabling multi-tenant support. Each platform reads only
  /// its own credentials object (Android reads [PushCredentials.android], iOS reads
  /// [PushCredentials.ios]) and ignores the other.
  ///
  /// If a Firebase app is already configured on the native side, it is deleted and
  /// re-initialized with the new credentials. This ensures the app stays connected
  /// to the correct FCM backend for the current tenant.
  ///
  /// Returns `true` if credentials were successfully applied, `false` otherwise.
  func setCredentials(credentials: PushCredentials, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Persists the Layrz device ID securely on the device.
  ///
  /// On Android, the device ID is encrypted using AES-GCM and stored in
  /// SharedPreferences backed by Android Keystore. On iOS, it is stored in
  /// Keychain (which survives app uninstall).
  ///
  /// The device ID defines the FCM topic that [subscribe] and [unsubscribe]
  /// will target, following the format `device_{deviceId}`.
  ///
  /// Must be called before [subscribe] and [unsubscribe]; they will return
  /// `false` if no device ID is set.
  ///
  /// Returns `true` if the device ID was successfully persisted, `false` otherwise.
  func setDeviceId(deviceId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Retrieves the persisted Layrz device ID from secure storage.
  ///
  /// On Android, the device ID is decrypted from AES-GCM-encrypted
  /// SharedPreferences (backed by Android Keystore). On iOS, it is retrieved
  /// from Keychain.
  ///
  /// Returns the device ID string if it was previously persisted via [setDeviceId].
  /// Returns null if no device ID has been set, if decryption fails (e.g., Android
  /// Auto Backup restored prefs on a new install without the Keystore key), or if
  /// the Keychain item is unavailable (e.g., on a different iOS device after backup).
  func getDeviceId(completion: @escaping (Result<String?, Error>) -> Void)
  /// Subscribes to the `device_{deviceId}` FCM topic.
  ///
  /// Requires both [setCredentials] and [setDeviceId] to have been called
  /// successfully first. If either is missing, this method returns `false`.
  ///
  /// On first subscribe after app install, FCM must fetch its registration token
  /// from Google Mobile Services (GMS). This can take a considerable time (observed
  /// up to 75 seconds) due to GMS communication and potential transient error
  /// retries. The returned Future completes once FCM finishes initialization.
  ///
  /// The subscription list is tracked locally; subsequent calls to [getSubscriptions]
  /// will reflect the newly added topic.
  ///
  /// Returns `true` if the subscription succeeded, `false` if credentials or device
  /// ID are missing, or if the native subscribe operation failed.
  func subscribe(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Unsubscribes from the `device_{deviceId}` FCM topic.
  ///
  /// Requires [setDeviceId] to have been called first. Returns `false` if no
  /// device ID is set or if the unsubscribe operation fails.
  ///
  /// The subscription list is tracked locally; subsequent calls to [getSubscriptions]
  /// will reflect the removal of the topic.
  ///
  /// Returns `true` if the unsubscription succeeded, `false` otherwise.
  func unsubscribe(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns the list of currently subscribed FCM topics.
  ///
  /// FCM does not provide a native API to query the full list of subscribed topics,
  /// so this plugin maintains a local list that is updated on each [subscribe] and
  /// [unsubscribe] call. This method returns that locally-tracked list.
  ///
  /// The list should contain topic strings like `device_12345` for subscribed topics.
  /// If no subscriptions exist, an empty list is returned.
  func getSubscriptions(completion: @escaping (Result<[String], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LayrzPushPlatformChannelSetup {
  static var codec: FlutterStandardMessageCodec { LayrzPushPigeonCodec.shared }
  /// Sets up an instance of `LayrzPushPlatformChannel` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LayrzPushPlatformChannel?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Injects (or replaces) the Firebase credentials at runtime.
    ///
    /// This method allows hot-swapping between different Firebase projects without
    /// restarting the app, enabling multi-tenant support. Each platform reads only
    /// its own credentials object (Android reads [PushCredentials.android], iOS reads
    /// [PushCredentials.ios]) and ignores the other.
    ///
    /// If a Firebase app is already configured on the native side, it is deleted and
    /// re-initialized with the new credentials. This ensures the app stays connected
    /// to the correct FCM backend for the current tenant.
    ///
    /// Returns `true` if credentials were successfully applied, `false` otherwise.
    let setCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialsArg = args[0] as! PushCredentials
        api.setCredentials(credentials: credentialsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setCredentialsChannel.setMessageHandler(nil)
    }
    /// Persists the Layrz device ID securely on the device.
    ///
    /// On Android, the device ID is encrypted using AES-GCM and stored in
    /// SharedPreferences backed by Android Keystore. On iOS, it is stored in
    /// Keychain (which survives app uninstall).
    ///
    /// The device ID defines the FCM topic that [subscribe] and [unsubscribe]
    /// will target, following the format `device_{deviceId}`.
    ///
    /// Must be called before [subscribe] and [unsubscribe]; they will return
    /// `false` if no device ID is set.
    ///
    /// Returns `true` if the device ID was successfully persisted, `false` otherwise.
    let setDeviceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.setDeviceId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDeviceIdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.setDeviceId(deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setDeviceIdChannel.setMessageHandler(nil)
    }
    /// Retrieves the persisted Layrz device ID from secure storage.
    ///
    /// On Android, the device ID is decrypted from AES-GCM-encrypted
    /// SharedPreferences (backed by Android Keystore). On iOS, it is retrieved
    /// from Keychain.
    ///
    /// Returns the device ID string if it was previously persisted via [setDeviceId].
    /// Returns null if no device ID has been set, if decryption fails (e.g., Android
    /// Auto Backup restored prefs on a new install without the Keystore key), or if
    /// the Keychain item is unavailable (e.g., on a different iOS device after backup).
    let getDeviceIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.getDeviceId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceIdChannel.setMessageHandler { _, reply in
        api.getDeviceId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeviceIdChannel.setMessageHandler(nil)
    }
    /// Subscribes to the `device_{deviceId}` FCM topic.
    ///
    /// Requires both [setCredentials] and [setDeviceId] to have been called
    /// successfully first. If either is missing, this method returns `false`.
    ///
    /// On first subscribe after app install, FCM must fetch its registration token
    /// from Google Mobile Services (GMS). This can take a considerable time (observed
    /// up to 75 seconds) due to GMS communication and potential transient error
    /// retries. The returned Future completes once FCM finishes initialization.
    ///
    /// The subscription list is tracked locally; subsequent calls to [getSubscriptions]
    /// will reflect the newly added topic.
    ///
    /// Returns `true` if the subscription succeeded, `false` if credentials or device
    /// ID are missing, or if the native subscribe operation failed.
    let subscribeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.subscribe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      subscribeChannel.setMessageHandler { _, reply in
        api.subscribe { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      subscribeChannel.setMessageHandler(nil)
    }
    /// Unsubscribes from the `device_{deviceId}` FCM topic.
    ///
    /// Requires [setDeviceId] to have been called first. Returns `false` if no
    /// device ID is set or if the unsubscribe operation fails.
    ///
    /// The subscription list is tracked locally; subsequent calls to [getSubscriptions]
    /// will reflect the removal of the topic.
    ///
    /// Returns `true` if the unsubscription succeeded, `false` otherwise.
    let unsubscribeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.unsubscribe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unsubscribeChannel.setMessageHandler { _, reply in
        api.unsubscribe { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      unsubscribeChannel.setMessageHandler(nil)
    }
    /// Returns the list of currently subscribed FCM topics.
    ///
    /// FCM does not provide a native API to query the full list of subscribed topics,
    /// so this plugin maintains a local list that is updated on each [subscribe] and
    /// [unsubscribe] call. This method returns that locally-tracked list.
    ///
    /// The list should contain topic strings like `device_12345` for subscribed topics.
    /// If no subscriptions exist, an empty list is returned.
    let getSubscriptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.layrz_push.LayrzPushPlatformChannel.getSubscriptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSubscriptionsChannel.setMessageHandler { _, reply in
        api.getSubscriptions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSubscriptionsChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API from Native to Flutter (via platform channels).
///
/// Provides a callback interface for the native platform to invoke Flutter
/// when events occur. This is implemented and set up by the Dart platform
/// implementation to receive foreground push notifications.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LayrzPushCallbackChannelProtocol {
  /// Called when a push notification arrives while the app is in foreground.
  ///
  /// This callback fires only when the app is actively running and visible to
  /// the user. When the app is in the background or terminated, the system will
  /// display the notification directly (with a system banner) and this callback
  /// will not be invoked.
  ///
  /// The [notification] contains the title, body, and custom data payload sent
  /// by the FCM backend.
  func onPush(notification notificationArg: PushNotification, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LayrzPushCallbackChannel: LayrzPushCallbackChannelProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LayrzPushPigeonCodec {
    return LayrzPushPigeonCodec.shared
  }
  /// Called when a push notification arrives while the app is in foreground.
  ///
  /// This callback fires only when the app is actively running and visible to
  /// the user. When the app is in the background or terminated, the system will
  /// display the notification directly (with a system banner) and this callback
  /// will not be invoked.
  ///
  /// The [notification] contains the title, body, and custom data payload sent
  /// by the FCM backend.
  func onPush(notification notificationArg: PushNotification, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.layrz_push.LayrzPushCallbackChannel.onPush\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([notificationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
